apiVersion: apps/v1
kind: Deployment
metadata:
  name: token
  namespace: wsi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
        node: app
    spec:
      containers:
        - name: token
          image: 702661606257.dkr.ecr.ap-northeast-2.amazonaws.com/token:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 0.6
              memory: 100Mi
            requests:
              cpu: 0.3
              memory: 100Mi