apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cicd-cluster
  region: ap-northeast-2 
  version: "1.29"

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-001fa0f3c0cef19db
      ap-northeast-2b:
        id: subnet-01dcff67b35fbffc6

managedNodeGroups:
  - name: app-nodegroup
    minSize: 2
    desiredCapacity: 2
    maxSize: 16
    labels:
      node: app
    instanceType: c5.large
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true