apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: wsi
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: rds-secret
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: "rds!db-52cde065-2659-4825-a711-20fe3ec6e423"
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: "rds!db-52cde065-2659-4825-a711-20fe3ec6e423"
      property: password