apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-secret
  namespace: wsi
spec:
  refreshInterval: 20s
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: rds-secret
  data:
  - secretKey: MYSQL_USER
    remoteRef:
      key: "rds!db-8388a17f-ce7d-4bac-8042-e801195e88b5"
      property: username
  - secretKey: MYSQL_PASSWORD
    remoteRef:
      key: "rds!db-8388a17f-ce7d-4bac-8042-e801195e88b5"
      property: password